<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_checkout</name>
   <tag></tag>
   <elementGuidId>aa6180b7-58f7-4976-b261-8b8d0b3683cb</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>input[name=&quot;checkout&quot;]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@name='checkout']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>003e6cae-f988-44cc-8717-6207b9c348c3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>submit</value>
      <webElementGuid>eb7cc4ed-6bcb-47db-aa0b-56a4526f1174</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>checkout</value>
      <webElementGuid>97dd1154-f26c-4850-9546-93eb47878f3a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>Finalizar Compra</value>
      <webElementGuid>b0821782-7924-4e75-a6fd-3da6c111916a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;tu-carrito&quot;)/main[1]/div[@class=&quot;clear carrito&quot;]/form[1]/div[@class=&quot;cart-total&quot;]/div[@class=&quot;botones&quot;]/input[2]</value>
      <webElementGuid>6d148133-2356-40f9-a8d3-14c0fa5d9bf5</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@name='checkout']</value>
      <webElementGuid>b53871fa-fe76-4fb5-893b-db371fe13131</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//body[@id='tu-carrito']/main/div/form/div[2]/div/input[2]</value>
      <webElementGuid>5087dc23-e704-4a3e-8dc0-2f673f6cdb28</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/input[2]</value>
      <webElementGuid>be138d7f-e1d3-425e-b3df-d5fa05a94501</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'submit' and @name = 'checkout']</value>
      <webElementGuid>54ce0d11-7a1b-47f7-a62e-b74deb440b94</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
