<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Ver Carrito</name>
   <tag></tag>
   <elementGuidId>d9742aff-8f4c-41bc-92a0-db571e46846f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>a.ver-carrito</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='minicart']/div[3]/a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>bd060da9-ee79-41c8-8339-025af76d1e39</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ver-carrito</value>
      <webElementGuid>eb69e969-7e33-4ffb-9503-9799016996d0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/cart</value>
      <webElementGuid>835b116f-d565-455e-9f28-54c7515274c9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Ver Carrito</value>
      <webElementGuid>e3fe3b35-ddc5-4aa8-b685-4d51642d4159</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;minicart&quot;)/div[@class=&quot;bottom&quot;]/a[@class=&quot;ver-carrito&quot;]</value>
      <webElementGuid>fe0ae5c0-e7bf-46d1-8cdb-f3f645854647</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='minicart']/div[3]/a</value>
      <webElementGuid>f758482c-ecfc-4996-8884-b54da0ec9aaf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Ver Carrito')]</value>
      <webElementGuid>dab4daed-e6e2-43ee-b7b0-853deea789cf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, '/cart')]</value>
      <webElementGuid>5bb4262d-90ab-4793-9443-9074813588cc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[6]/div/div[3]/a</value>
      <webElementGuid>b6d646de-d5ec-4600-846c-7236513a714d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '/cart' and (text() = 'Ver Carrito' or . = 'Ver Carrito')]</value>
      <webElementGuid>5b684d3e-b1db-4c70-8e6d-29c727c59971</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
