<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_customerpassword</name>
   <tag></tag>
   <elementGuidId>cada92e3-1366-4ef8-bcd9-e3874afae2af</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#CreatePassword</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='CreatePassword']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>23cd3a6f-fe09-4a32-befb-c3b04843c705</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>password</value>
      <webElementGuid>cc16c240-a72e-4a95-a79e-175ac34d3190</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>customer[password]</value>
      <webElementGuid>5d47cd7e-0937-4c88-830a-4343d1a380f6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>CreatePassword</value>
      <webElementGuid>925234bd-f3ef-421f-8f76-ccde219736ab</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Contraseña</value>
      <webElementGuid>b5e61943-77b6-469d-a10d-91f27b5ddb0d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;CreatePassword&quot;)</value>
      <webElementGuid>121ef4f9-ae72-402c-8d05-fefedbf486ae</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='CreatePassword']</value>
      <webElementGuid>ff331304-717e-4ae0-a2cb-92d9e0c302d0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='create_customer']/div[4]/input</value>
      <webElementGuid>78de6841-20bf-43af-b371-47761fa4ae32</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/input</value>
      <webElementGuid>2147f70e-6561-405d-9833-81ce3fabc853</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'password' and @name = 'customer[password]' and @id = 'CreatePassword' and @placeholder = 'Contraseña']</value>
      <webElementGuid>35f11b00-c67f-4bcc-8f0c-1cff260bd2be</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
