<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>iframe_c-6ls5kdd7tse5</name>
   <tag></tag>
   <elementGuidId>045b62bc-f7dc-4562-bd5e-054843a86f73</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>iframe[name=&quot;c-6ls5kdd7tse5&quot;]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//iframe[@name='c-6ls5kdd7tse5']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>iframe</value>
      <webElementGuid>50fc99ab-7cc5-496d-82e2-dccac697dbf5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>El reCAPTCHA caduca dentro de dos minutos</value>
      <webElementGuid>40d6927e-8fc3-4d83-a321-c133d49391c3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>c-6ls5kdd7tse5</value>
      <webElementGuid>8e417a82-92f1-4200-b684-56ceb6975b52</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>frameborder</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>dbb59f81-4b42-4378-b910-9ff430c99695</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>scrolling</name>
      <type>Main</type>
      <value>no</value>
      <webElementGuid>9a3e5c47-31a0-4cc0-a430-e325fb2b7f19</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>sandbox</name>
      <type>Main</type>
      <value>allow-forms allow-popups allow-same-origin allow-scripts allow-top-navigation allow-modals allow-popups-to-escape-sandbox allow-storage-access-by-user-activation</value>
      <webElementGuid>a0d8c473-75a6-46ab-b49f-8e0536cd8e3a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://www.recaptcha.net/recaptcha/api2/bframe?hl=es&amp;v=-QbJqHfGOUB8nuVRLvzFLVed&amp;k=6LeoeSkTAAAAAA9rkZs5oS82l69OEYjKRZAiKdaF</value>
      <webElementGuid>56d1366b-9f4b-43bc-98c6-8865a2779e34</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;desafio&quot;)/div[10]/div[4]/iframe[1]</value>
      <webElementGuid>834158b2-9955-4a1d-9dc7-078e90103800</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//iframe[@name='c-6ls5kdd7tse5']</value>
      <webElementGuid>518a8d59-c63a-44a8-900d-d0c930d7c393</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//body[@id='desafio']/div[10]/div[4]/iframe</value>
      <webElementGuid>dea1d743-93cb-41a3-8007-4e98a7ac501a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/iframe</value>
      <webElementGuid>dd8ae9e6-45bd-44fd-8afe-4c0540321f53</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//iframe[@title = 'El reCAPTCHA caduca dentro de dos minutos' and @name = 'c-6ls5kdd7tse5' and @src = 'https://www.recaptcha.net/recaptcha/api2/bframe?hl=es&amp;v=-QbJqHfGOUB8nuVRLvzFLVed&amp;k=6LeoeSkTAAAAAA9rkZs5oS82l69OEYjKRZAiKdaF']</value>
      <webElementGuid>710e44a7-c46f-4064-b036-8684a9fd4ad8</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
