<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>iframe_a-6ls5kdd7tse5</name>
   <tag></tag>
   <elementGuidId>69e570cf-51bb-4a0c-ab5b-426537684d35</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>iframe[name=&quot;a-6ls5kdd7tse5&quot;]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//iframe[@name='a-6ls5kdd7tse5']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>iframe</value>
      <webElementGuid>9e7475d6-584f-48d9-835b-041b2d4d4490</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>reCAPTCHA</value>
      <webElementGuid>bf55eac9-c768-490f-a3a4-f9a20cfb8e5a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>width</name>
      <type>Main</type>
      <value>304</value>
      <webElementGuid>d57bef48-11c7-4c7f-b98c-b176c777c77a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>height</name>
      <type>Main</type>
      <value>78</value>
      <webElementGuid>f453b769-d5fe-4481-a0a7-a4af1deb25e5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>presentation</value>
      <webElementGuid>ba58b9a3-d7bb-42a5-b725-7ca27fab1eaf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>a-6ls5kdd7tse5</value>
      <webElementGuid>401b20c6-8f20-4820-9f24-0a9ca24459d4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>frameborder</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>b95593a6-e6ab-4ab1-ab00-449a3127f3ba</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>scrolling</name>
      <type>Main</type>
      <value>no</value>
      <webElementGuid>966177b4-36de-4a39-a13a-c063eb73fb73</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>sandbox</name>
      <type>Main</type>
      <value>allow-forms allow-popups allow-same-origin allow-scripts allow-top-navigation allow-modals allow-popups-to-escape-sandbox allow-storage-access-by-user-activation</value>
      <webElementGuid>366f0dfe-43a5-44a1-8ccd-86eebd4b84aa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://www.recaptcha.net/recaptcha/api2/anchor?ar=1&amp;k=6LeoeSkTAAAAAA9rkZs5oS82l69OEYjKRZAiKdaF&amp;co=aHR0cHM6Ly9naWZ0c2hvcGthd2FpaS5jbDo0NDM.&amp;hl=es&amp;v=-QbJqHfGOUB8nuVRLvzFLVed&amp;size=normal&amp;cb=b4o7wm25vpok</value>
      <webElementGuid>d3fbaf0c-fa34-4dd0-938b-c358975a6ccb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;g-recaptcha&quot;)/div[1]/div[1]/iframe[1]</value>
      <webElementGuid>6d6efe17-cc93-4e5b-a0f5-b8a23509cd89</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//iframe[@name='a-6ls5kdd7tse5']</value>
      <webElementGuid>34774ef5-3e13-4519-8c3e-b007268e8d5c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='g-recaptcha']/div/div/iframe</value>
      <webElementGuid>2d58bf7b-49b3-48fb-8744-7d1cc2f6d045</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//iframe</value>
      <webElementGuid>5ab2f8d1-a0ee-4e2a-879b-45c2de54b55c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//iframe[@title = 'reCAPTCHA' and @name = 'a-6ls5kdd7tse5' and @src = 'https://www.recaptcha.net/recaptcha/api2/anchor?ar=1&amp;k=6LeoeSkTAAAAAA9rkZs5oS82l69OEYjKRZAiKdaF&amp;co=aHR0cHM6Ly9naWZ0c2hvcGthd2FpaS5jbDo0NDM.&amp;hl=es&amp;v=-QbJqHfGOUB8nuVRLvzFLVed&amp;size=normal&amp;cb=b4o7wm25vpok']</value>
      <webElementGuid>467a6eb2-6852-4ff8-9a43-158409e29c8a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
