<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_rc-image-tile-33</name>
   <tag></tag>
   <elementGuidId>5b6f71be-4dd3-4943-985e-fa4a0670f469</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>img.rc-image-tile-33</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='rc-imageselect-target']/table/tbody/tr/td/div/div/img</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>017c4bd7-c662-4584-850e-460274195e29</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>rc-image-tile-33</value>
      <webElementGuid>0a5373ea-3562-4306-915d-d52b5c9b4df1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://www.recaptcha.net/recaptcha/api2/payload?p=06AFcWeA6YIxIEfHQGtZlydA_VIE06KrLxOZO_3ALYBr4BqXy7LSvRhVny3pZDCYAKtUEPEnZs6LkYraS19sfYV6JZnO-DQXLwT9lj75ttJx-08ycH54TGhE0nO20dJ4Q7zErUoiYHL7TuyekTsAypTMG5lDBqbQPToToKrPhgk_88NJrY7Qy99nVuUAhzHHZOxYEPb7jhuOra&amp;k=6LeoeSkTAAAAAA9rkZs5oS82l69OEYjKRZAiKdaF</value>
      <webElementGuid>db1e40a8-c2e1-411c-ac66-ec12a924c79b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;rc-imageselect-target&quot;)/table[@class=&quot;rc-imageselect-table-33&quot;]/tbody[1]/tr[1]/td[@class=&quot;rc-imageselect-tile&quot;]/div[@class=&quot;rc-image-tile-target&quot;]/div[@class=&quot;rc-image-tile-wrapper&quot;]/img[@class=&quot;rc-image-tile-33&quot;]</value>
      <webElementGuid>81718533-9bde-44a1-aee6-1cf5ad512aca</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Page_Desafo  Gift Shop Kawaii/iframe_c-6ls5kdd7tse5</value>
      <webElementGuid>2fd6956d-3f74-407a-8445-f725c2c69f4b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='rc-imageselect-target']/table/tbody/tr/td/div/div/img</value>
      <webElementGuid>6729ab3b-6f6c-4ccc-8419-65474046dfcb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>//img[contains(@src,'https://www.recaptcha.net/recaptcha/api2/payload?p=06AFcWeA6YIxIEfHQGtZlydA_VIE06KrLxOZO_3ALYBr4BqXy7LSvRhVny3pZDCYAKtUEPEnZs6LkYraS19sfYV6JZnO-DQXLwT9lj75ttJx-08ycH54TGhE0nO20dJ4Q7zErUoiYHL7TuyekTsAypTMG5lDBqbQPToToKrPhgk_88NJrY7Qy99nVuUAhzHHZOxYEPb7jhuOra&amp;k=6LeoeSkTAAAAAA9rkZs5oS82l69OEYjKRZAiKdaF')]</value>
      <webElementGuid>72ba4e6c-0316-4ec4-8931-a420e0654648</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//img</value>
      <webElementGuid>35f8bc36-1098-4b6b-a35a-f1f97f2f0282</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = 'https://www.recaptcha.net/recaptcha/api2/payload?p=06AFcWeA6YIxIEfHQGtZlydA_VIE06KrLxOZO_3ALYBr4BqXy7LSvRhVny3pZDCYAKtUEPEnZs6LkYraS19sfYV6JZnO-DQXLwT9lj75ttJx-08ycH54TGhE0nO20dJ4Q7zErUoiYHL7TuyekTsAypTMG5lDBqbQPToToKrPhgk_88NJrY7Qy99nVuUAhzHHZOxYEPb7jhuOra&amp;k=6LeoeSkTAAAAAA9rkZs5oS82l69OEYjKRZAiKdaF']</value>
      <webElementGuid>e6986d27-0f5c-4dc3-8eb4-54c814b87240</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
