<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_shopify-challenge__button btn</name>
   <tag></tag>
   <elementGuidId>f5f2d6e1-5984-4950-9528-63b5ba6befe5</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>input.shopify-challenge__button.btn</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@value='Enviar']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>a3e2ae71-f007-4992-b38d-a6d3034b9574</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>submit</value>
      <webElementGuid>49fdb25e-2d44-4348-8e55-c763cea199d3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>Enviar</value>
      <webElementGuid>f78b2c43-8396-4ce1-a708-2c8aaaa3c200</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>shopify-challenge__button btn</value>
      <webElementGuid>c3c63324-453d-4786-a9ac-c74ca47e0a40</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;desafio&quot;)/main[1]/div[@class=&quot;shopify-challenge__container&quot;]/form[1]/input[@class=&quot;shopify-challenge__button btn&quot;]</value>
      <webElementGuid>2a52f2b6-d1a6-46cb-bc1b-484e8212136a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@value='Enviar']</value>
      <webElementGuid>5fe3ae00-80b0-467f-9bde-cd3a2ac2a492</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//body[@id='desafio']/main/div/form/input[2]</value>
      <webElementGuid>8a5a1c39-bf47-4604-9515-34016090e034</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//main/div/form/input[2]</value>
      <webElementGuid>285d3154-2bc1-46d2-bf80-46bd75c17c3d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'submit']</value>
      <webElementGuid>4b2db5b3-c592-4a11-a823-5b1c62e3bb89</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
