<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_dos</name>
   <tag></tag>
   <elementGuidId>74806466-28cc-4625-a67a-5f8db287f1db</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>img.dos</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//body[@id='ropa-y-accesorios']/main/div/div/div[2]/ul/li/a/div/img[2]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>64e91d84-5675-4017-8002-80743eee3e3c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>dos</value>
      <webElementGuid>2634fd28-7a1d-44f2-b315-e40e9eab58f0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>//giftshopkawaii.cl/cdn/shop/products/IMG_8323_large.jpg?v=1618090314</value>
      <webElementGuid>39908951-5dbd-4c17-8b12-958a0545b721</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ropa-y-accesorios&quot;)/main[1]/div[@class=&quot;featured-collection&quot;]/div[@class=&quot;clear&quot;]/div[@class=&quot;all-coll&quot;]/ul[1]/li[@class=&quot;item one-quarter small--one-half&quot;]/a[1]/div[@class=&quot;img&quot;]/img[@class=&quot;dos&quot;]</value>
      <webElementGuid>ab264872-ecb6-480b-9e71-e3616d9fb60e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//body[@id='ropa-y-accesorios']/main/div/div/div[2]/ul/li/a/div/img[2]</value>
      <webElementGuid>65fc2f37-4583-4d2f-aa4d-cbdb01bb3a77</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//img[2]</value>
      <webElementGuid>37a08e10-950a-4829-ac88-7dde2f739aff</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = '//giftshopkawaii.cl/cdn/shop/products/IMG_8323_large.jpg?v=1618090314']</value>
      <webElementGuid>e1c5ad42-bd3f-41d4-9468-146e1fb0dfa9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//body[@id='ropa-y-accesorios']/main/div/div/div[2]/ul/li[11]/a/div/img[2]</value>
      <webElementGuid>79c58a68-8ae1-44a7-8ea1-97bff98565de</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
