<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_dos</name>
   <tag></tag>
   <elementGuidId>0dba9cc5-b83b-4c83-9948-4c385b7a0ef7</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//body[@id='aros']/main/div/div/div[2]/ul/li[8]/a/div/img[2]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>a8dd81c7-6a5f-45d2-b8eb-f0d2ba861cde</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>dos</value>
      <webElementGuid>f8518998-9b2c-4726-982f-3b2424d207af</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>//giftshopkawaii.cl/cdn/shop/products/IMG_8323_large.jpg?v=1618090314</value>
      <webElementGuid>fceece06-e407-4ae4-824e-5c6d5064d2fb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;aros&quot;)/main[1]/div[@class=&quot;featured-collection&quot;]/div[@class=&quot;clear&quot;]/div[@class=&quot;all-coll&quot;]/ul[1]/li[@class=&quot;item one-quarter small--one-half&quot;]/a[1]/div[@class=&quot;img&quot;]/img[@class=&quot;dos&quot;]</value>
      <webElementGuid>f9fe257f-742d-43c6-8014-4669087af8c3</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//body[@id='aros']/main/div/div/div[2]/ul/li[8]/a/div/img[2]</value>
      <webElementGuid>07c8aab1-a8e7-492c-a802-7f37bf483dea</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[8]/a/div/img[2]</value>
      <webElementGuid>29dec276-063b-42d6-b4de-8c045c52bbc1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = '//giftshopkawaii.cl/cdn/shop/products/IMG_8323_large.jpg?v=1618090314']</value>
      <webElementGuid>27d4166a-1353-48f5-92a5-1683581f815c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
