<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_email</name>
   <tag></tag>
   <elementGuidId>1ddc9ea0-376f-4efa-aa3b-6c3a20a319fa</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#RecoverEmail</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='RecoverEmail']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>3511737b-48d6-4a91-88a4-2f1e1e65abf6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>email</value>
      <webElementGuid>2c08b292-4167-41c6-aeda-33c8fab519a2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>email</value>
      <webElementGuid>f3e1c0bc-5a99-4491-af11-321f39ef8849</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>RecoverEmail</value>
      <webElementGuid>af91104d-56a1-442f-8c84-da16adaacf0c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Escribe aquí tu email</value>
      <webElementGuid>f3e1933d-e5da-4060-ade0-668abdc953d8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocorrect</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>5aa9fbc0-b413-47b0-96b0-88c6a5186e0b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocapitalize</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>765c9048-0247-414f-9a4c-5d0e66d05279</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;RecoverEmail&quot;)</value>
      <webElementGuid>79fe0ab2-5ba5-4056-890c-a2869d7f1a7f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='RecoverEmail']</value>
      <webElementGuid>2494b2bd-d5a5-4ca6-919d-5af392dd170d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='RecoverPasswordForm']/form/div/input</value>
      <webElementGuid>0d28fbe0-fbba-4ee5-b568-e171c31ad971</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/form/div/input</value>
      <webElementGuid>8ad92ac9-822f-4057-8851-4594fae7c54f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'email' and @name = 'email' and @id = 'RecoverEmail' and @placeholder = 'Escribe aquí tu email']</value>
      <webElementGuid>b3c901f7-9f4a-43df-b84d-e853ba795421</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
