<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_customeremail</name>
   <tag></tag>
   <elementGuidId>c4e58b50-13f8-4ffa-8491-a48a1bb1c394</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#CustomerEmail</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='CustomerEmail']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>4637ad09-bd2a-45a9-b0ea-9750267b0be9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>email</value>
      <webElementGuid>b399f308-9c27-482b-8ec3-511a8cebd65c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>customer[email]</value>
      <webElementGuid>3bfc0046-07bd-42ad-80f5-25bb84566457</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>CustomerEmail</value>
      <webElementGuid>f06b017a-8d97-42d0-bb09-2dbb6abd33d9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Escribe tu email</value>
      <webElementGuid>9cf67180-d311-48e1-981d-3320ee62eddd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocorrect</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>11935d30-19f2-458c-a838-d296a2c18d63</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocapitalize</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>2c2800ca-70a2-4e04-875b-70e704f2f3cd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;CustomerEmail&quot;)</value>
      <webElementGuid>41d2a1cf-38d9-4306-9c46-578a5798cef8</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='CustomerEmail']</value>
      <webElementGuid>1edb71c1-8e87-46fc-8a45-7fd09cbed682</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='customer_login']/div/input</value>
      <webElementGuid>c283fde6-8e1c-43a7-bf17-8cf8f0379222</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/input</value>
      <webElementGuid>754c0df4-0b06-428e-ba37-5591b2dce2a2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'email' and @name = 'customer[email]' and @id = 'CustomerEmail' and @placeholder = 'Escribe tu email']</value>
      <webElementGuid>4c3cd6e4-7c72-4240-bf40-b839a3d44df9</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
