<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_city_1</name>
   <tag></tag>
   <elementGuidId>c949fcbc-0c67-4f43-b71a-f01c17fd7daf</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#TextField4</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='TextField4']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>cf77e9b4-6c00-443a-93a5-97ba3d5095f2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>TextField4</value>
      <webElementGuid>7efd4a63-50ac-432b-9e59-856873994470</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>city</value>
      <webElementGuid>5aa10eb3-0740-4f36-bdf5-986180a6e595</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>bbd5f033-264d-4331-bdea-e3b0baf0fc61</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-required</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>84a49716-e11b-43a9-b600-d467e6ae9559</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-labelledby</name>
      <type>Main</type>
      <value>TextField4-label</value>
      <webElementGuid>462a0dde-6d7a-430c-83f3-66cbd5d51b36</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>shipping address-level2</value>
      <webElementGuid>a440e697-feff-4775-8b9f-aec985c9ea48</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>_7ozb2uq _1frageme0 _1fragemm2 _1fragemhb _1fragemlc _7ozb2ur _7ozb2uv _1fragemlr _1fragemlm _1fragemm0 _7ozb2u11 _7ozb2u1j</value>
      <webElementGuid>b916fee2-1387-4b89-9c55-b8b581276d22</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;TextField4&quot;)</value>
      <webElementGuid>15b058cd-867a-491b-97bb-397f8321f673</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='TextField4']</value>
      <webElementGuid>615df139-c38c-40c4-86b6-c7c6018235ea</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='shippingAddressForm']/div/div/div[5]/div[2]/div/div/input</value>
      <webElementGuid>ce1a61c2-b1c5-40d8-ac41-c18d319f0543</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[5]/div[2]/div/div/input</value>
      <webElementGuid>6ec26861-81d4-4711-8e96-76d2496a1055</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'TextField4' and @name = 'city' and @type = 'text']</value>
      <webElementGuid>9967a28a-c776-462d-9c4f-167df828f1dd</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
