<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_address1</name>
   <tag></tag>
   <elementGuidId>b473e552-0e5d-418d-9824-11e2559cd588</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#TextField2</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='TextField2']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>07593ec7-85ee-4116-b16c-67229605b26f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>TextField2</value>
      <webElementGuid>fad4dac6-a46a-4ca5-bfc6-e60a0d81f9ef</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>address1</value>
      <webElementGuid>24f10899-617c-49b4-bb9d-9f9b8d312762</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Dirección</value>
      <webElementGuid>79fb0617-fcbb-44b1-bc34-fad2caa08056</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>50fbc5d3-dfcf-4123-bbc0-a9e6f4c11b96</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-required</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>d36cb28f-7148-4a83-b46f-74cbff53ac5a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-labelledby</name>
      <type>Main</type>
      <value>TextField2-label</value>
      <webElementGuid>e1915820-30e0-4ff7-9e73-9161f9bccd74</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>shipping address-line1</value>
      <webElementGuid>a70e587a-a248-4e2f-afdc-48f54a109b20</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-protected-input</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>ebb0efda-cab6-47c3-89ce-306a31792bd0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>_7ozb2uq _1frageme0 _1fragemm2 _1fragemhb _1fragemlc _7ozb2ur _7ozb2u11 _7ozb2u1j</value>
      <webElementGuid>2c248213-522b-4db7-862d-05a70325c029</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;TextField2&quot;)</value>
      <webElementGuid>7831f543-9ab4-4ef4-b976-4f0e1121eef2</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='TextField2']</value>
      <webElementGuid>d43fe35f-9f92-4863-b14f-7e21e5bc927f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='shippingAddressForm']/div/div/div[3]/div/div/div/div/div/input</value>
      <webElementGuid>5bf9c1f8-4c61-482d-b2d2-d44a32e317c8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/div/div/div/div/input</value>
      <webElementGuid>e771acae-fa79-4397-849c-d28aa9ada789</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'TextField2' and @name = 'address1' and @placeholder = 'Dirección' and @type = 'text']</value>
      <webElementGuid>f552f389-ae39-4eb2-a6d3-f7d480bd8576</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
