<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_city</name>
   <tag></tag>
   <elementGuidId>957f373c-c1e5-42a1-8703-0693da3f0187</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#TextField4</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='TextField4']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>a7de2871-dbac-4795-90d4-3c346b7e970b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>TextField4</value>
      <webElementGuid>19d6fc2f-fce1-49e3-b331-6dacb3b18897</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>city</value>
      <webElementGuid>ba3bb066-3cbf-4418-a7f1-6755d493957b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Comuna</value>
      <webElementGuid>f22f687b-78e5-4ee1-87cb-c7b9911fc492</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>80df84f7-3821-4766-98a2-07fa95cc78df</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-required</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>9ff300ca-9c3f-4065-83aa-19bda32e8562</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-labelledby</name>
      <type>Main</type>
      <value>TextField4-label</value>
      <webElementGuid>ab5982c4-3d5a-4dfd-b4e8-d99c3685cb72</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>shipping address-level2</value>
      <webElementGuid>bfd67069-c5d5-4810-a9f9-fb8758d92884</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>_7ozb2uq _1frageme0 _1fragemm2 _1fragemhb _1fragemlc _7ozb2ur _7ozb2u11 _7ozb2u1j</value>
      <webElementGuid>065fc032-42d7-4835-ba8c-c15aeeefb284</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;TextField4&quot;)</value>
      <webElementGuid>1a530377-739a-4728-bfc8-fe7088e9a576</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='TextField4']</value>
      <webElementGuid>2960489e-4d0c-4a8a-af34-5452d07c1fbb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='shippingAddressForm']/div/div/div[5]/div[2]/div/div/input</value>
      <webElementGuid>82339d8a-58a9-400b-9e42-e6a86b25acd4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[5]/div[2]/div/div/input</value>
      <webElementGuid>5ea25e5e-3b0c-45d5-bd68-2755007fcc36</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'TextField4' and @name = 'city' and @placeholder = 'Comuna' and @type = 'text']</value>
      <webElementGuid>7e9809e3-6816-4e85-a76d-80e4d92cbf39</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
