<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_Arica y ParinacotaTarapacAntofagasta_d758bf</name>
   <tag></tag>
   <elementGuidId>0352ae98-3059-4018-b534-4baf5e4287b9</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#Select1</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='Select1']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>ada43619-f5ed-4603-aa69-c2737f3ab3df</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>zone</value>
      <webElementGuid>8b80f69a-0fe3-4047-baf7-b60f02c69bec</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>Select1</value>
      <webElementGuid>7e064e5a-b5e0-45d4-bee5-b73f886af605</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>shipping address-level1</value>
      <webElementGuid>f7c8e1f1-77f0-4f74-be8c-b36108e40caf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>_b6uH _1fragemm8 yA4Q8 vYo81 RGaKd</value>
      <webElementGuid>4119aaab-0d51-4565-9643-e80084f92f3c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value> Arica y ParinacotaTarapacáAntofagastaAtacamaCoquimboValparaísoSantiagoO’HigginsMauleÑubleBiobíoAraucaníaLos RíosLos LagosAysénMagallanes</value>
      <webElementGuid>5c959fd8-f8bb-4298-9a90-e6df852e3cf7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;Select1&quot;)</value>
      <webElementGuid>9000d8fd-81be-4667-b846-94732e82c981</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='Select1']</value>
      <webElementGuid>24d059b6-2291-4346-97fc-87d33fcbd6af</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='shippingAddressForm']/div/div/div[6]/div/div/div/select</value>
      <webElementGuid>98ee73b7-4fc7-40f4-b8bf-428046b12458</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[6]/div/div/div/select</value>
      <webElementGuid>5f6dcd09-38f6-4fec-a00f-a874f688f4f1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@name = 'zone' and @id = 'Select1' and (text() = ' Arica y ParinacotaTarapacáAntofagastaAtacamaCoquimboValparaísoSantiagoO’HigginsMauleÑubleBiobíoAraucaníaLos RíosLos LagosAysénMagallanes' or . = ' Arica y ParinacotaTarapacáAntofagastaAtacamaCoquimboValparaísoSantiagoO’HigginsMauleÑubleBiobíoAraucaníaLos RíosLos LagosAysénMagallanes')]</value>
      <webElementGuid>aa7737aa-421a-40f5-869e-4fae1cc35d42</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
