<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Contacto</name>
   <tag></tag>
   <elementGuidId>3b5ae9df-631f-4cbf-8553-b20ab56fdce2</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.item.one-fifth.small--one-whole > ul > li:nth-of-type(3) > a</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='shopify-section-footer']/footer/div/div[4]/ul/li[3]/a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>1dd0eeb1-762b-4c01-9e1e-8b3386eb212a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/pages/contacto</value>
      <webElementGuid>1655e95c-4639-4356-92c3-c7eb7d29b887</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Contacto</value>
      <webElementGuid>5e30084a-f7a9-413d-a89a-06ed6ddd2d39</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;shopify-section-footer&quot;)/footer[1]/div[@class=&quot;clear&quot;]/div[@class=&quot;item one-fifth small--one-whole&quot;]/ul[1]/li[3]/a[1]</value>
      <webElementGuid>97de6543-3b8a-4960-9316-144a60701f88</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='shopify-section-footer']/footer/div/div[4]/ul/li[3]/a</value>
      <webElementGuid>10cbc326-df96-4b3a-99f6-50fbccb4c693</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Contacto')]</value>
      <webElementGuid>dd80a1c4-7c2f-4e44-b52b-eae5274b9ea9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, '/pages/contacto')]</value>
      <webElementGuid>3f92d52e-a0be-45c4-9663-8af2dfb3be68</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//footer/div/div[4]/ul/li[3]/a</value>
      <webElementGuid>14a642dc-913d-4c21-8203-f633037650e3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '/pages/contacto' and (text() = 'Contacto' or . = 'Contacto')]</value>
      <webElementGuid>20ee950c-5bce-445b-8241-9834556a44cf</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
