<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Usericon</name>
   <tag></tag>
   <elementGuidId>7734fb6d-0211-4a15-acb8-b649e6d999fa</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>a.user > i</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>/html/body/div[3]/header/div[1]/div[4]/ul/li[2]/a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>i</value>
      <webElementGuid>51ca67ba-fac2-487f-a9cb-9e3a97456117</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;shopify-section-header&quot;)/header[1]/div[@class=&quot;row1&quot;]/div[@class=&quot;icons&quot;]/ul[1]/li[2]/a[@class=&quot;user&quot;]/i[1]</value>
      <webElementGuid>c68e1242-732c-44e7-bde6-f5920eee4924</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>/html/body/div[3]/header/div[1]/div[4]/ul/li[2]/a</value>
      <webElementGuid>5489f19d-1b9d-4ae8-9af7-b999daba84b6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/ul/li[2]/a/i</value>
      <webElementGuid>a057f6f7-6632-4e81-af2c-346cd51a4ee7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='shopify-section-header']/header/div/div[4]/ul/li[2]/a/i</value>
      <webElementGuid>e35ea0dc-c7a5-40de-a597-3025a4c8e3ea</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
