<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_q</name>
   <tag></tag>
   <elementGuidId>53abc77d-d81c-479a-bf3c-d8ca2ae6a303</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.buscador > form.right > #search-field</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>(//input[@id='search-field'])[2]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>924cccc9-9c0e-469f-8a2e-1fc914b2def7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>q</value>
      <webElementGuid>33661a92-5265-43b4-9480-61c4e559601e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>search</value>
      <webElementGuid>9099bf01-7a32-471c-aa39-53349f9a8d7f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>search-field</value>
      <webElementGuid>0f3c6971-413d-48d9-932c-b5c2c7e5c361</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>¿Qué quieres buscar?</value>
      <webElementGuid>8791dd5a-f895-4cf3-b82a-b673800199e3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;shopify-section-header&quot;)/header[1]/div[@class=&quot;row1&quot;]/div[@class=&quot;buscador&quot;]/form[@class=&quot;right&quot;]/input[@id=&quot;search-field&quot;]</value>
      <webElementGuid>4dcd1442-54dc-439b-a103-c84df1b09207</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//input[@id='search-field'])[2]</value>
      <webElementGuid>f535cce2-8233-407e-b288-42b004340a48</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='shopify-section-header']/header/div/div[5]/form/input</value>
      <webElementGuid>8fd3aa5f-c039-40da-bd90-6299e39c4997</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[5]/form/input</value>
      <webElementGuid>69d1fe43-fb12-435b-91d3-37adbf354b11</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@name = 'q' and @type = 'search' and @id = 'search-field' and @placeholder = '¿Qué quieres buscar?']</value>
      <webElementGuid>18cfa37b-d7b4-4041-b608-1d8068d77522</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
