<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_contactemail</name>
   <tag></tag>
   <elementGuidId>f34c65a9-0523-4783-957e-1c57397b7998</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#ContactFormEmail</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='ContactFormEmail']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>e9f3158a-5970-4183-a46f-57d043f66d1c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>email</value>
      <webElementGuid>bd55447b-539a-4579-93fe-effad565f6c4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>ContactFormEmail</value>
      <webElementGuid>1d5077c1-feb8-4ad9-8ace-ee5409992251</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>contact[email]</value>
      <webElementGuid>ad7411b2-a9a1-456e-ae9c-60d25cc12874</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Email</value>
      <webElementGuid>69dfb281-c1d9-4a90-80a0-91486347834f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocorrect</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>847666e9-9ce8-4b38-9d5b-cc87a595aa72</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocapitalize</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>7b7fbe8d-3bb7-4457-9969-4f13e930bf1c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ContactFormEmail&quot;)</value>
      <webElementGuid>624839a8-84ef-4d89-811d-85e542fdc7af</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='ContactFormEmail']</value>
      <webElementGuid>49ebb37a-f500-48b9-beff-1f3ceaca06ce</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='contact_form']/div/input[2]</value>
      <webElementGuid>8f621942-0bfe-4012-8629-197ef57d73d5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/input[2]</value>
      <webElementGuid>aefc5100-6121-4ce0-b201-51aef2e27d7c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'email' and @id = 'ContactFormEmail' and @name = 'contact[email]' and @placeholder = 'Email']</value>
      <webElementGuid>3c45c12b-4c4a-48ee-8cef-9e811cf905f7</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
